id: blacksmith-sharpstone-iii
display:
  name: '&fSharpening Stone &aIII'
  material: FLINT
type: 'generic'
tags:
  - consumable
lore:
  - ''
  - '&eFor &f5 &eminutes, your basic attacks'
  - '&edeal &f5 &eadditional damage!'
triggers:
  right: 'item-consume'
extra:
  duration: 300
  damage-buff: 5
  requiredLevel: 40
  experience: 5000
