id: greater-crafted-potion-sacred-fire
display:
  name: '&6Greater Crafted Potion of Sacred Fire'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eYour spells have a &f25% &echance to burn'
  - '&eenemies for an additional &f100 &emagic î'
  - '&edamage for &f25 &eminutes!'
triggers:
  right: 'item-consume'
extra:
  amount: 100
  chance: 25
  duration: 1500
  color: orange
  requiredLevel: 60
  experience: 5000
