id: enchanter-powder-ii
display:
  name: '&fPotent Magic Powder'
  material: GLOWSTONE_DUST
type: 'generic'
tags:
  - consumable
lore:
  - '&eFor 60 seconds, your magic î attacks'
  - '&edeal 8 additional damage!'
triggers:
  right: 'item-consume'
extra:
  experience: 850
  requiredLevel: 15
  effect: 8
  duration: 60

