id: enchanter-powder-iii
display:
  name: '&fBlackened Magic Powder'
  material: GLOWSTONE_DUST
type: 'generic'
tags:
  - consumable
lore:
  - '&eFor 60 seconds, your magic î attacks'
  - '&edeal 10 additional damage!'
triggers:
  right: 'item-consume'
extra:
  experience: 2000
  requiredLevel: 30
  effect: 10
  duration: 60

