id: enchanter-powder-i
display:
  name: '&fBrittle Magic Powder'
  material: GLOWSTONE_DUST
type: 'generic'
tags:
- consumable
lore:
- '&eFor 60 seconds, your magic î attacks'
- '&edeal 6 additional damage!'
triggers:
  right: 'item-consume'
data:
  experience: 350
  requiredLevel: 0
  effect: 6
  duration: 60
  
