id: greater-crafted-potion-haste
display:
  name: '&aGreater Crafted Potion of Haste'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eIncreases mining speed by &f40%'
  - '&efor &f25 &eminutes'
triggers:
  right: 'item-consume'
extra:
  multiplier: 1
  duration: 1500
  color: lime
  requiredLevel: 60
  experience: 9000
