id: greater-potion-mana
display:
  name: '&3Greater Potion of Mana'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eRestores &3225✸ &eon use'
triggers:
  right: 'item-consume'
extra:
  amount: 225
  color: aqua
