id: 'lightbrown-steed'
display:
  name: '&eLightbrown Steed'
  material: SADDLE
tags:
  - 'untradeable'
type: 'generic'
lore:
  - ''
  - '&6Tier: &7Normal'
  - '&6Speed: +&725%'
  - ''
  - '&r&7&oA loyal and valiant steed!'
triggers:
  right: 'summon-mount'
extra:
  mount-id: LIGHTBROWN_STEED
