id: minor-crafted-potion-haste
display:
  name: '&aMinor Crafted Potion of Haste'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eIncreases mining speed by &f20%'
  - '&efor &f15 &eminutes'
triggers:
  right: 'item-consume'
extra:
  multiplier: 0
  duration: 900
  color: lime
  requiredLevel: 25
  experience: 2750
