id: minor-potion-mana
display:
  name: '&3Minor Potion of Mana'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eRestores &375✸ &eon use'
triggers:
  right: 'item-consume'
extra:
  amount: 75
  color: aqua
