id: misty-alcove-minor-potion-healing
display:
  name: '&cMinor Potion of Healing'
  material: POTION
type: 'generic'
tags:
  - potion
lore:
  - ''
  - '&eRestores &c75<3 &eon use'
triggers:
  right: 'item-consume'
extra:
  amount: 75
  color: red
