id: misty-alcove-minor-potion-mana
display:
  name: '&3Minor Potion of Mana'
  material: POTION
type: 'generic'
tags:
- potion
lore:
- ''
- '&eRestores &375✸ &eon use'
triggers:
  right: 'item-consume'
data:
  amount: 75
  color: aqua
