id: 'mount-black-steed'
display:
  name: '&eBlack Steed'
  material: SADDLE
tags:
- 'untradeable'
type: 'generic' 
lore:
  - ''
  - '&r&7Consume this item to unlock this mount!'
triggers:
  right: 'summon-mount'
data:
  mount-id: BLACK_STEED

