id: 'mount-infernal-charger'
display:
  name: '&eInfernal Charger'
  material: SADDLE
tags:
- 'untradeable'
type: generic
lore:
  - ''
  - '&r&7Consume this item to unlock this mount!'
triggers:
  right: 'summon-mount'
data:
  mount-id: INFERNAL_CHARGER
