id: 'mount-blackfrost-kitsune'
display:
  name: '&eBlackfrost Kitsune'
  material: SADDLE
tags:
  - 'untradeable'
type: generic
lore:
  - ''
  - '&r&7Consume this item to unlock this mount!'
triggers:
  right: 'summon-mount'
extra:
  mount-id: BLACKFROST_KITSUNE
