id: 'mount-capybara'
display:
  name: '&eCapybara'
  material: SADDLE
tags:
  - 'untradeable'
type: generic
lore:
  - ''
  - '&r&7Consume this item to unlock this mount!'
triggers:
  right: 'summon-mount'
extra:
  mount-id: CAPYBARA
