id: 'mount-white-stallion'
display:
  name: '&eWhite Stallion'
  material: SADDLE
tags:
  - 'untradeable'
type: 'generic'
lore:
  - ''
  - '&r&7Consume this item to unlock this mount!'
triggers:
  right: 'summon-mount'
extra:
  mount-name: 'White Stallion'
  mount-type: 'HORSE'
  horse-color: 'WHITE'
  mount-speed: '4'
