id: tracking-scroll
display:
  name: '&fTracking Scroll'
  material: PURPLE_DYE
type: 'generic'
tags:
  - consumable
lore:
  - ''
  - '&eLearn the location of a player!'
triggers:
  right: 'item-consume'
extra:
  cooldown: 30
