id: whetstone
display:
  name: '&fWhetstone'
  material: FLINT
type: 'generic'
tags:
  - consumable
lore:
  - ''
  - '&eFor 3 minutes, your basic attacks'
  - '&edeal 3 additional damage!'
triggers:
  right: 'item-consume'
extra:
  duration: 180
  damage-buff: 3
